### PR TITLE
Feature/rip slp

### PR DESCRIPTION
**Pull request by Surgeonito**

### CODE REVIEW

**Review by allisonle — APPROVED** [review]
Looks good, please bump the version to `0.3.1` here before merging: [https://github.com/Bitcoin-com/bitcoincom-link/blob/master/package.json#L3](https://github.com/Bitcoin-com/bitcoincom-link/blob/master/package.json#L3)

**Comment by PorlyBe** [comment]
> Looks good, please bump the version to `0.3.1` here before merging: https://github.com/Bitcoin-com/bitcoincom-link/blob/master/package.json#L3

I suggest 0.4.0 because there's breaking change

**Comment by Surgeonito** [comment]
@PorlyBe just merge? no speciall actions here?

**Comment by allisonle** [comment]
@Surgeonito I can publish the package to NPM once it's merged

**Pull request merged**
